version: "3"

services:
  phoenix:
    build:
      context: .
      dockerfile: ./docker/phoenix.dockerfile
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    depends_on:
      - pgdatabase
  pgdatabase:
    container_name: hyperion_pgdatabase
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: hyperion_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - pgdatabase